stages:
  - train

train-model:
  stage: train
  script:
    - echo "## Training...." >> logger.md

    - echo "Copy `logo.png` to `train` folder for example" >> logger.md
    - mkdir -p train
    - cp logo.png train/

    - echo "# Trained completed successfully" >> logger.md
    - echo "Send notification to Kay server" >> logger.md
    - echo "Push new model to this " $CI_COMMIT_BRANCH  >> logger.md
    - git add .
    - echo "$CI_PROJECT_PATH " $CI_PROJECT_PATH
    - git commit -m "Trained successfully"
    - git remote show origin
    - git remote set-url --push origin git@gitlab-fpt:$CI_PROJECT_PATH
    - git remote show origin
    - git push --follow-tags origin HEAD:$CI_COMMIT_REF_NAME -o ci.skip
  tags:
    - worker