stages:
  - train

train-model:
  stage: train
  script:
    - echo "## Training...." >> logger.md

    - echo "Copy `logo.png` to `train` folder for example" >> logger.md
    - mkdir -p train
    - cp logo.png train/

    - echo "# Trained completed successfully" >> logger.md
    - echo "Send notification to Kay server" >> logger.md
    - echo "Push new model to this " $CI_COMMIT_BRANCH  >> logger.md
    - git add .
    - git commit -m "Trained successfully"
    - git push -o ci.skip
  tags:
    - worker