stages:
  - train

train-model:
  stage: train
  script:
    - echo "## Training...."
    - echo "$CI_PROJECT_PATH"
    - echo "CI_COMMIT_BRANCH:" $CI_COMMIT_BRANCH 
    - start run.bat

    # Push new model back to the repository.
    - cd $CI_BUILDS_DIR
    - git add .
    - git commit -m "Trained successfully"
    - git remote show origin
    - git remote set-url --push origin git@gitlab.com-fpt:$CI_PROJECT_PATH
    - git remote show origin
    - git push --follow-tags origin HEAD:$CI_COMMIT_REF_NAME -o ci.skip
  tags:
    - worker